name: Pull Request Checks

on:
  pull_request:
    branches:
      - '**'
      - '!main'  # You can exclude the main branch from triggering this if desired.

env:
  SOLUTION_FILE: ./TestProject.sln

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: |
          dotnet restore ${{ env.SOLUTION_FILE }}

      - name: Run tests
        run: |
          dotnet test ${{ env.SOLUTION_FILE }} --no-restore --verbosity normal

      - name: Upload test results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestProject.Tests/TestResults/